import {
  designGenerationFromServer,
  type DesignGeneration,
} from '@/features/design-my-space/design-generation';
import { API_BASE_URL } from '@/constants/config';
import { ApiError, apiRequest } from '@/services/api-client';

/**
 * ROOM VISUALIZATION ENDPOINTS — network only.
 *
 * Every call carries the signed-in user's token; the backend scopes each query
 * by the authenticated id, so another user's generation is a 404. The request
 * body is exactly two ids and a retry key: no board configuration, no prompt,
 * no status, no owner.
 */

type GenerationResponse = { success: true; generation?: unknown };
type GenerationsResponse = { success: true; generations?: unknown; page?: unknown; hasMore?: unknown; total?: unknown };

function generationOrThrow(response: GenerationResponse | null): DesignGeneration {
  const generation = designGenerationFromServer(response?.generation);
  if (!generation) throw new ApiError('unknown', 'The server returned an unreadable visualization.');
  return generation;
}

/**
 * POST /api/design-generations → 202 Accepted (queued), or 200 when this
 * `idempotencyKey` already created one.
 *
 * Nothing is generated by this call.
 */
export async function createDesignGeneration(
  token: string,
  input: { boardId: string; roomPhotoId: string; idempotencyKey: string }
): Promise<DesignGeneration> {
  const response = await apiRequest<GenerationResponse>('/design-generations', {
    method: 'POST',
    token,
    body: { boardId: input.boardId, roomPhotoId: input.roomPhotoId, idempotencyKey: input.idempotencyKey },
  });
  return generationOrThrow(response);
}

/** GET /api/design-generations — this user's history, newest first. */
export async function fetchDesignGenerations(
  token: string,
  options: { page?: number; limit?: number } = {}
): Promise<{ generations: DesignGeneration[]; hasMore: boolean }> {
  const query = new URLSearchParams();
  if (options.page) query.set('page', String(options.page));
  if (options.limit) query.set('limit', String(options.limit));
  const suffix = query.toString() ? `?${query}` : '';

  const response = await apiRequest<GenerationsResponse>(`/design-generations${suffix}`, { token });
  if (!Array.isArray(response?.generations)) {
    throw new ApiError('unknown', 'The server returned an unreadable list of visualizations.');
  }

  // One unreadable entry is skipped, never allowed to hide the rest.
  const generations = response.generations
    .map(designGenerationFromServer)
    .filter((generation): generation is DesignGeneration => generation !== null);

  return { generations, hasMore: response.hasMore === true };
}

/** GET /api/design-generations/:id */
export async function fetchDesignGeneration(token: string, id: string): Promise<DesignGeneration> {
  return generationOrThrow(await apiRequest<GenerationResponse>(`/design-generations/${id}`, { token }));
}

/**
 * How `expo-image` loads a generated visualization: from the API, with the
 * Bearer token as a header, never from a storage URL. The endpoint answers
 * only the owner of a succeeded generation, so this source is useless to
 * anyone else — and it is built on demand, never stored.
 */
export function designGenerationImageSource(token: string, id: string) {
  return {
    uri: `${API_BASE_URL}/design-generations/${id}/image`,
    headers: { Authorization: `Bearer ${token}` },
  };
}

/** DELETE /api/design-generations/:id — never deletes the room photo it used. */
export async function deleteDesignGeneration(token: string, id: string): Promise<void> {
  await apiRequest(`/design-generations/${id}`, { method: 'DELETE', token });
}
